version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=anderson
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=marketcashier
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

# Somente para o BD