#!/bin/bash
cleanBuild() {
	echo "Removendo arquivos compilados de 'static/'"
	rm -rf static/*
}

case $1 in
    build)
        echo "Construindo aplicativo..."

        # Para comprimir os estáticos deve-se desabilitar o modo debug.
        export DEBUG_MODE=False

        cleanBuild

        echo "Coletando arquivos estáticos..."
        python manage.py collectstatic -c --no-input

        #echo "Compressing static files..."
        #python manage.py compress
    ;;
    *)
        echo "Iniciando Cecane"

        cleanBuild
        
        export ENV_FILE=dev.env

        python manage.py runserver 0.0.0.0:1313
    ;;
esac