# Generated by Django 5.0 on 2023-12-18 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255, verbose_name='Nome do Produto')),
                ('estoque', models.FloatField(default=1.0, verbose_name='Estoque do Produto')),
                ('preco', models.FloatField(default=1.0, verbose_name='Valor do Quilo ou Unidade')),
                ('unidadePeso', models.BooleanField(default=True, editable=False, verbose_name='Unidade?')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField(default=1.0, verbose_name='Quantidade')),
                ('valorTotal', models.FloatField(default=1.0, verbose_name='Valor da Total')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens das vendas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(default=1.0, verbose_name='Valor da Compra')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('finalizado', models.BooleanField(default=False, editable=False, verbose_name='Finalizado?')),
                ('pago', models.BooleanField(default=False, editable=False, verbose_name='Pago?')),
                ('ativo', models.BooleanField(default=True, editable=False, verbose_name='Ativo?')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cliente', verbose_name='Cliente')),
                ('itens', models.ManyToManyField(to='controle.itemvenda', verbose_name='Itens da Compra')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['id', 'dataCadastro'],
            },
        ),
    ]
