# Generated by Django 5.0 on 2023-12-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_venda_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controle.venda', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidadePeso',
            field=models.BooleanField(default=True, verbose_name='Unidade?'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado?'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
    ]
