# Generated by Django 5.0 on 2023-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_remove_venda_itens_itemvenda_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Código do Produto'),
        ),
    ]
