# Generated by Django 5.0 on 2024-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_pagamento_remove_venda_pago_venda_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(default=0.0, verbose_name='Valor da Compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.TextField(blank=True, max_length=25, null=True, unique=True, verbose_name='Código do Produto'),
        ),
    ]
